services:
  bot:
    build: .
    restart: always
    environment:
      - SCHEDULE_BOT_TOKEN=1687593023:AAHt-sOFxPDgoTZKDsmYn2Lkr7C1FD6nSJo
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
